import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import Nav from "@/components/nav";
import Footer from "@/components/footer";

import ThemeProvider from "@/context/themeProvder";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" forcedTheme="dark">
          <Nav />
          <main className="bg-white dark:bg-black">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
